// TODO Fix Quorum

import { Address, BigInt } from "@graphprotocol/graph-ts";
import {
  NounsAgoraGovernorSepolia,
  ProposalCanceled,
  ProposalCreated,
  ProposalExecuted,
  VoteCast,
  Initialized,
} from "../generated/NounsAgoraGovernorSepolia/NounsAgoraGovernorSepolia";
import {
  _handleDroposalCreated,
  _handleDroposalCanceled,
  _handleDroposalExecuted,
  _handleDroposalVoteCast,
  getDroposal,
} from "./handlers";
import { Droposal, DroposalType } from "../generated/schema";
import { DroposalState } from "./utils/constants";

export function handleInitialized(event: Initialized): void {
  let standardDroposalType = new DroposalType(
    event.transaction.hash.concatI32(event.logIndex.toI32() + 1)
  );
  standardDroposalType.name = "Standard";
  standardDroposalType.save();

  let premiumDroposalType = new DroposalType(
    event.transaction.hash.concatI32(event.logIndex.toI32() + 1)
  );
  premiumDroposalType.name = "Premium";
  premiumDroposalType.save();

  // TODO flesh out the other objectives
  //   entity.droposalTypeId = event.params.droposalTypeId;
  //   entity.config_name = event.params.config.name;
  //   entity.config_editionSize = event.params.config.editionSize;
  //   entity.config_publicSalePrice = event.params.config.publicSalePrice;
  //   entity.config_publicSaleDuration = event.params.config.publicSaleDuration;
  //   entity.config_fundsRecipientSplit = event.params.config.fundsRecipientSplit;
  //   entity.config_minter = event.params.config.minter;
  //   entity.blockNumber = event.block.number;
  //   entity.blockTimestamp = event.block.timestamp;
  //   entity.transactionHash = event.transaction.hash;
  //   entity.save();
}

export function handleProposalCanceled(event: ProposalCanceled): void {
  _handleDroposalCanceled(event.params.proposalId.toString(), event);
}

// Handle the Proposal ie: Droposal Created event from the Nouns
// Agora Governor
export function handleProposalCreated(event: ProposalCreated): void {
  // Pull quorum from the NounsAgoraGovernor
  const contract = NounsAgoraGovernorSepolia.bind(event.address);
  const quorumVotes = contract.quorum(event.block.number);

  _handleDroposalCreated(
    event.params.proposalId.toString(),
    event.params.proposer.toHexString(),
    event.params.targets,
    event.params.values,
    event.params.signatures,
    event.params.calldatas,
    event.params.startBlock,
    event.params.endBlock,
    event.params.description,
    quorumVotes,
    event
  );
}

// ProposalExecuted(proposalId)
export function handleProposalExecuted(event: ProposalExecuted): void {
  _handleDroposalExecuted(event.params.proposalId.toString(), event);
}

// VoteCast(account, proposalId, support, weight, reason);
export function handleVoteCast(event: VoteCast): void {
  const droposal = getLatestDroposalValues(
    event.params.proposalId.toString(),
    event.address,
    event.block.number
  );

  // Proposal will be updated as part of handler
  _handleDroposalVoteCast(
    droposal,
    event.params.voter.toHexString(),
    event.params.weight,
    event.params.reason,
    event.params.support,
    event
  );
}

function getLatestDroposalValues(
  droposalId: string,
  contractAddress: Address,
  blockNumber: BigInt
): Droposal {
  const droposal = getDroposal(droposalId);

  // Pull quorum from the NounsAgoraGovernor
  const contract = NounsAgoraGovernorSepolia.bind(contractAddress);
  const quorumVotes = contract.quorum(blockNumber);

  // On first vote, set state and quorum values
  if (droposal.state == DroposalState.PENDING) {
    droposal.state = DroposalState.ACTIVE;
    droposal.quorumVotes = quorumVotes;
  }
  return droposal;
}

// TODO keep or remove the autogenerated code form the NounsAgoraGovernor ABI

// export function handleDroposalTypeProposed(
//   event: DroposalTypeProposedEvent
// ): void {
//   let entity = new DroposalTypeProposed(
//     event.transaction.hash.concatI32(event.logIndex.toI32())
//   );
//   entity.droposalTypeId = event.params.droposalTypeId;
//   entity.config_name = event.params.config.name;
//   entity.config_editionSize = event.params.config.editionSize;
//   entity.config_publicSalePrice = event.params.config.publicSalePrice;
//   entity.config_publicSaleDuration = event.params.config.publicSaleDuration;
//   entity.config_fundsRecipientSplit = event.params.config.fundsRecipientSplit;
//   entity.config_minter = event.params.config.minter;

//   entity.blockNumber = event.block.number;
//   entity.blockTimestamp = event.block.timestamp;
//   entity.transactionHash = event.transaction.hash;

//   entity.save();
// }

// export function handleDroposalTypeSet(event: DroposalTypeSetEvent): void {
//   let entity = new DroposalTypeSet(
//     event.transaction.hash.concatI32(event.logIndex.toI32())
//   );
//   entity.droposalTypeId = event.params.droposalTypeId;
//   entity.config_name = event.params.config.name;
//   entity.config_editionSize = event.params.config.editionSize;
//   entity.config_publicSalePrice = event.params.config.publicSalePrice;
//   entity.config_publicSaleDuration = event.params.config.publicSaleDuration;
//   entity.config_fundsRecipientSplit = event.params.config.fundsRecipientSplit;
//   entity.config_minter = event.params.config.minter;

//   entity.blockNumber = event.block.number;
//   entity.blockTimestamp = event.block.timestamp;
//   entity.transactionHash = event.transaction.hash;

//   entity.save();
// }

// export function handleOwnershipTransferred(
//   event: OwnershipTransferredEvent
// ): void {
//   let entity = new OwnershipTransferred(
//     event.transaction.hash.concatI32(event.logIndex.toI32())
//   );
//   entity.previousOwner = event.params.previousOwner;
//   entity.newOwner = event.params.newOwner;

//   entity.blockNumber = event.block.number;
//   entity.blockTimestamp = event.block.timestamp;
//   entity.transactionHash = event.transaction.hash;

//   entity.save();
// }

// export function handleProposalThresholdSet(
//   event: ProposalThresholdSetEvent
// ): void {
//   let entity = new ProposalThresholdSet(
//     event.transaction.hash.concatI32(event.logIndex.toI32())
//   );
//   entity.oldProposalThreshold = event.params.oldProposalThreshold;
//   entity.newProposalThreshold = event.params.newProposalThreshold;

//   entity.blockNumber = event.block.number;
//   entity.blockTimestamp = event.block.timestamp;
//   entity.transactionHash = event.transaction.hash;

//   entity.save();
// }

// export function handleUpgraded(event: UpgradedEvent): void {
//   let entity = new Upgraded(
//     event.transaction.hash.concatI32(event.logIndex.toI32())
//   );
//   entity.implementation = event.params.implementation;

//   entity.blockNumber = event.block.number;
//   entity.blockTimestamp = event.block.timestamp;
//   entity.transactionHash = event.transaction.hash;

//   entity.save();
// }

// export function handleVoteCast(event: VoteCastEvent): void {
//   let entity = new VoteCast(
//     event.transaction.hash.concatI32(event.logIndex.toI32())
//   );
//   entity.voter = event.params.voter;
//   entity.proposalId = event.params.proposalId;
//   entity.support = event.params.support;
//   entity.weight = event.params.weight;
//   entity.reason = event.params.reason;

//   entity.blockNumber = event.block.number;
//   entity.blockTimestamp = event.block.timestamp;
//   entity.transactionHash = event.transaction.hash;

//   entity.save();
// }

// export function handleVoteCastWithParams(event: VoteCastWithParamsEvent): void {
//   let entity = new VoteCastWithParams(
//     event.transaction.hash.concatI32(event.logIndex.toI32())
//   );
//   entity.voter = event.params.voter;
//   entity.proposalId = event.params.proposalId;
//   entity.support = event.params.support;
//   entity.weight = event.params.weight;
//   entity.reason = event.params.reason;
//   entity.params = event.params.params;

//   entity.blockNumber = event.block.number;
//   entity.blockTimestamp = event.block.timestamp;
//   entity.transactionHash = event.transaction.hash;

//   entity.save();
// }

// export function handleVotingDelaySet(event: VotingDelaySetEvent): void {
//   let entity = new VotingDelaySet(
//     event.transaction.hash.concatI32(event.logIndex.toI32())
//   );
//   entity.oldVotingDelay = event.params.oldVotingDelay;
//   entity.newVotingDelay = event.params.newVotingDelay;

//   entity.blockNumber = event.block.number;
//   entity.blockTimestamp = event.block.timestamp;
//   entity.transactionHash = event.transaction.hash;

//   entity.save();
// }

// export function handleVotingPeriodSet(event: VotingPeriodSetEvent): void {
//   let entity = new VotingPeriodSet(
//     event.transaction.hash.concatI32(event.logIndex.toI32())
//   );
//   entity.oldVotingPeriod = event.params.oldVotingPeriod;
//   entity.newVotingPeriod = event.params.newVotingPeriod;

//   entity.blockNumber = event.block.number;
//   entity.blockTimestamp = event.block.timestamp;
//   entity.transactionHash = event.transaction.hash;

//   entity.save();
// }

// export function handleAdminChanged(event: AdminChangedEvent): void {
//   let entity = new AdminChanged(
//     event.transaction.hash.concatI32(event.logIndex.toI32())
//   );
//   entity.previousAdmin = event.params.previousAdmin;
//   entity.newAdmin = event.params.newAdmin;

//   entity.blockNumber = event.block.number;
//   entity.blockTimestamp = event.block.timestamp;
//   entity.transactionHash = event.transaction.hash;

//   entity.save();
// }

// export function handleBeaconUpgraded(event: BeaconUpgradedEvent): void {
//   let entity = new BeaconUpgraded(
//     event.transaction.hash.concatI32(event.logIndex.toI32())
//   );
//   entity.beacon = event.params.beacon;

//   entity.blockNumber = event.block.number;
//   entity.blockTimestamp = event.block.timestamp;
//   entity.transactionHash = event.transaction.hash;

//   entity.save();
// }
